### ISSUE TITLE
startView option not working

### ISSUE THREAD

**Issue by KaurKirikall** [rajit/bootstrap3-datepicker#25] opened 2016-04-10 05:01 UTC
I'm trying to achieve the startView with milleniums for birth dates, but the option just does not work with any of the possible values. Also tried other options for startView, but the option of startView just seems to be broken.

```
Template.Profile.onRendered( function(){
	$(document).ready(function () {
		$("#birthdateField").datepicker({
			autoclose: true,
			orientation: "bottom",
			startView: 4
		});
	});
});

**Comment by KaurKirikall** [comment] 2016-04-10 07:43
Also using 
`defaultViewDate: {year:2000, month:0, day:1}`
option seems to break it and not work. Insteads sets date to 1923 February

**Comment by rajit** [comment] 2016-04-19 08:44
Hi @KaurKirikall. The startView can only be set to 0, 1 or 2.

Here is what each option does:

* 0 = month view
* 1 = year view
* 2 = decade view

Have a look at eternicode's online demo to understand it better: http://eternicode.github.io/bootstrap-datepicker/

> Also using 
> defaultViewDate: {year:2000, month:0, day:1}
> option seems to break it and not work. Insteads sets date to 1923 February

I cannot reproduce this. If I set `defaultViewDate: { year: 2000, month: 0, day: 1 }` then the picker opens to January 2000.

If you share a repository with me that reproduces the issue then I can help you figure out the problem.

**Comment by rajit** [comment] 2016-04-19 08:45
I will close this issue as the `startView` option is hopefully resolved.

Please open a new issue if you'd like to look into the `defaultViewDate` further.

**Closed by rajit** 2016-04-19 08:45 UTC
