### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dates' of undefined

### ISSUE THREAD

**Issue by digitalfrost** [rajit/bootstrap3-datepicker#13] opened 2015-09-12 17:42 UTC
Getting the following error using the bootstrap3-datepicker-fr package

```
Uncaught TypeError: Cannot read property 'dates' of undefined(anonymous function) 
@ bootstrap-datepicker.fr.min.js:1(anonymous function) 
@ bootstrap-datepicker.fr.min.js:1(anonymous function) 
@ rajit_bootstrap3-datepicker-fr.js?39f3534c69768438ad0eddf23a5133507f1892d4:36(anonymous function) 
@ rajit_bootstrap3-datepicker-fr.js?39f3534c69768438ad0eddf23a5133507f1892d4:43
```

**Comment by Xsandor** [comment] 2015-10-06 13:49
I experience the same thing with *bootstrap3-datepicker-sv*
```
Uncaught TypeError: Cannot read property 'dates' of undefined(anonymous function)
@ rajit_bootstrap3-datepicker-sv.js:9(anonymous function) @ rajit_bootstrap3-datepicker-sv.js:9(anonymous function) 
@ rajit_bootstrap3-datepicker-sv.js:12(anonymous function) 
@ rajit_bootstrap3-datepicker-sv.js?70d15fd564d6426a696638b23860db87cb667407:41(anonymous function) 
@ rajit_bootstrap3-datepicker-sv.js?70d15fd564d6426a696638b23860db87cb667407:48
```

**Comment by rajit** [comment] 2015-10-08 07:42
How are you reproducing this issue?

I have built a simple Meteor project using an English datepicker, a French datepicker and a Swedish datepicker.

You can see all three date pickers, with different languages presented. There are no JavaScript errors.

Here is the project: https://github.com/rajit/bootstrap3-datepicker-example

**Comment by Xsandor** [comment] 2015-10-08 07:58
I will try to reproduce it later today.

I am using your package together with aldeed:autoform-bs-datepicker. I'll
see if that has something to do with it.

tors 8 okt 2015 09:42 Rajit Singh <notifications@github.com> skrev:

> How are you reproducing this issue?
>
> I have built a simple Meteor project using an English datepicker, a French
> datepicker and a Swedish datepicker.
>
> You can see all three date pickers, with different languages presented.
> There are no JavaScript errors.
>
> Here is the project:
> https://github.com/rajit/bootstrap3-datepicker-example
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rajit/bootstrap3-datepicker/issues/13#issuecomment-146446617>
> .
>
-- 

Hälsningar
Alexander Schmidt
Karlborgs Elkontroll AB
0733 500 797

**Comment by rajit** [comment] 2015-10-08 08:06
Thanks! If you manage to reproduce it, I'd appreciate it if you could share the project with me.

**Comment by Xsandor** [comment] 2015-10-09 11:02
I haven't been able to reproduce it. But I managed to get rid of the error in my own application by doing this:

`meteor remove aldeed:autoform-bs-datepicker rajit:bootstrap3-datepicker rajit:bootstrap3-datepicker-sv`
`meteor add rajit:bootstrap3-datepicker rajit:bootstrap3-datepicker-sv`
`meteor add aldeed:autoform-bs-datepicker`

I'm not sure why it would be fixed by removing and adding the packages.

**Comment by rajit** [comment] 2015-10-09 11:43
Thanks for looking into it, glad you figured it out!

**Closed by rajit** 2015-10-09 11:43 UTC

**Comment by FuggyD** [comment] 2017-01-11 07:19
I got the same message: Uncaught TypeError: Cannot read property 'dates' of undefined(anonymous function)
My fault was that I include the locale before the datepicker. After I changed the order it worked fine!

**Comment by rajit** [comment] 2017-01-11 17:35
Thanks for sharing @FuggyD!

**Comment by Juanjo4U** [comment] 2019-11-13 10:57
I got the answer of that error which is that if you are trying to read a property of and object or json that is null you are doing it wrong, you better initialize it with some value, for example:
obj = null   ----- obj.name   ---- error,  Cannot read property 'dates' of undefined
obj = {}    ---obj.name ----no error, but you don't get any value because it doesn't exists
obj = {
     alumno: Juanjo,
     profesor: Pablo Monteserin,
}              
-------obj.alumno----- Juanjo--- you got the value because it exists

**Comment by rajit** [comment] 2019-11-13 14:00
Thanks for sharing @Juanjo4U, hopefully that helps someone
